Fog Machine
musehq/muse-ideas pull request #10
Opened 2022-09-05 21:00 UTC by alex-shortt

a machine to let you change the fog for the world. saves the previously set fog and will reset it when disabled / removed

2022-09-05 22:40 UTC, alex-shortt commented
muse push for id `6f3c92ab-5d1f-4019-84f2-07632045d1ed`

2022-09-05 22:48 UTC, veltsonbastien requested changes

2022-09-05 22:48 UTC, veltsonbastien commented on src/ideas/decorations/FogMachine/index.tsx
> +    return () => {
couldn't this just be `return lastFog.current` ?

2022-09-05 22:48 UTC, veltsonbastien commented on src/ideas/decorations/FogMachine/index.tsx
> +          position-y={0.01}
since you have position y and z you could do `position={[0,0.01,0.7]}`

2022-09-05 22:48 UTC, veltsonbastien commented on src/ideas/decorations/FogMachine/index.tsx
> +        <Suspense fallback={null}>
there is also another `enabled &&` on line 63, you could put this Suspense into that same condition

2022-09-06 00:06 UTC, alex-shortt commented
feedback
- maybe lower volume / distance / falloff model of audio

2022-09-06 16:21 UTC, merged